### ISSUE TITLE
Please choose a license

### ISSUE THREAD

**Issue by devkev** [eccherda/ch552g_mini_keyboard#1]
Thanks for all the excellent info and work here!  I also have a few of these devices, and [figured out how to program keys with the stock firmware in Linux](https://github.com/devkev/hid-minikb-libusb).  But I'm definitely looking forward to flashing your much better firmware onto them, and maybe even trying to improve on it (eg. make the LED colors controllable from the computer).  So that this is possible, can you please choose an open source license and apply it to your firmware?  Github's https://choosealicense.com/ site can help with this if necessary.

**Comment by eccherda** [comment]
Hi, thank you for your interest. I've added the Creative Commons Attribution-ShareAlike 3.0 license, as that was the license of the code portions I started with.
